"""Model package. Importing this module registers every table on Base.metadata.

Alembic relies on this to autogenerate migrations; without it the metadata is
empty and no table would be created.
"""
from app.models.entities import (
    AIStructuredNote,
    AITranscription,
    Allergy,
    Appointment,
    AuditLog,
    BreakGlassEvent,
    CareTeamAccess,
    Consent,
    Consultation,
    Document,
    Encounter,
    Medication,
    Message,
    NoteVersion,
    Notification,
    Observation,
    Organization,
    Patient,
    Payment,
    Professional,
    Referral,
    SignalingMessage,
    Subscription,
    SupportTicket,
    Teleconsultation,
    User,
    VerificationRequest,
    WebhookEvent,
)

__all__ = [
    "AIStructuredNote",
    "AITranscription",
    "Allergy",
    "Appointment",
    "AuditLog",
    "BreakGlassEvent",
    "CareTeamAccess",
    "Consent",
    "Consultation",
    "Document",
    "Encounter",
    "Medication",
    "Message",
    "NoteVersion",
    "Notification",
    "Observation",
    "Organization",
    "Patient",
    "Payment",
    "Professional",
    "Referral",
    "SignalingMessage",
    "Subscription",
    "SupportTicket",
    "Teleconsultation",
    "User",
    "VerificationRequest",
    "WebhookEvent",
]
