/**
 * Icon language for SunuDoctor.
 *
 * One coherent set (Lucide, outline + rounded) so every screen speaks the same
 * visual vocabulary. Icons are semantic, not decorative: the same concept always
 * maps to the same glyph across the product.
 */
export {
  // Navigation / structure
  LayoutDashboard as IconHome,
  Users as IconPatients,
  Stethoscope as IconConsultation,
  AudioLines as IconScribe,
  Video as IconTeleconsultation,
  MessagesSquare as IconMessages,
  FileText as IconDocuments,
  Network as IconCoordination,
  Bell as IconNotifications,
  Wallet as IconPayments,
  Wallet as IconBilling,
  ShieldCheck as IconSecurity,
  User as IconProfile,
  Settings as IconSettings,
  // Actions
  Plus as IconAdd,
  Search as IconSearch,
  Mic as IconMic,
  Square as IconStop,
  Play as IconPlay,
  Pause as IconPause,
  Check as IconCheck,
  CheckCircle2 as IconCheckCircle,
  X as IconClose,
  RotateCcw as IconRetry,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  Download as IconDownload,
  Upload as IconUpload,
  Send as IconSend,
  Filter as IconFilter,
  ChevronRight as IconChevronRight,
  ChevronDown as IconChevronDown,
  ArrowRight as IconArrowRight,
  ArrowLeft as IconArrowLeft,
  ExternalLink as IconExternalLink,
  // Domain
  Languages as IconLanguage,
  Sparkles as IconAI,
  AlertTriangle as IconWarning,
  Info as IconInfo,
  Clock as IconClock,
  Calendar as IconCalendar,
  HeartPulse as IconVitals,
  Pill as IconMedication,
  Activity as IconActivity,
  ClipboardList as IconRecords,
  ShieldAlert as IconBreakGlass,
  ShieldAlert as IconShieldAlert,
  Lock as IconLock,
  Wifi as IconOnline,
  WifiOff as IconOffline,
  Signal as IconLimited,
  Building2 as IconStructure,
  Building2 as IconBuilding2,
  LogOut as IconLogout,
  Menu as IconMenu,
  CircleDot as IconDot,
  FileCheck2 as IconValidated,
  Ban as IconRejected,
} from "lucide-react";
