"""add identity verification and facility registry

Revision ID: 3b39316f4d73
Revises: 5b93c4a876e4
Create Date: 2026-10-02 06:55:38.817444
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3b39316f4d73'
down_revision: str | None = '5b93c4a876e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('official', 'partner', 'manual', 'community', name='registrysourcetype'), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('received', 'validated', 'review', 'published', 'rejected', name='registryimportstatus'), nullable=False),
    sa.Column('imported_by', sa.String(length=36), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healthcare_facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('hospital', 'eps', 'health_center', 'health_post', 'health_hut', 'clinic', 'medical_practice', 'paramedical_practice', 'laboratory', 'imaging_center', 'community_health_structure', 'specialized_facility', 'military_facility', 'paramilitary_facility', 'other', name='facilitytype'), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('commune', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('official_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('official', 'partner', 'manual', 'community', name='registrysourcetype'), nullable=False),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('official_verified', 'partner_verified', 'pending_verification', 'unverified', 'inactive', 'archived', name='facilitystatus'), nullable=False),
    sa.Column('registry_import_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_import_id'], ['registry_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_facilities_district'), 'healthcare_facilities', ['district'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_name'), 'healthcare_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_official_id'), 'healthcare_facilities', ['official_id'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_region'), 'healthcare_facilities', ['region'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_status'), 'healthcare_facilities', ['status'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_type'), 'healthcare_facilities', ['type'], unique=False)
    op.create_table('identity_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_documents_professional_id'), 'identity_documents', ['professional_id'], unique=False)
    op.create_table('professional_duplicate_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('matched_professional_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_duplicate_flags_matched_professional_id'), 'professional_duplicate_flags', ['matched_professional_id'], unique=False)
    op.create_index(op.f('ix_professional_duplicate_flags_professional_id'), 'professional_duplicate_flags', ['professional_id'], unique=False)
    op.create_table('verification_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('from_level', sa.String(length=32), nullable=True),
    sa.Column('to_level', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_consulted', sa.String(length=255), nullable=True),
    sa.Column('match_result', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_decisions_professional_id'), 'verification_decisions', ['professional_id'], unique=False)
    op.create_table('facility_admin_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_admin_grants_facility_id'), 'facility_admin_grants', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_admin_grants_user_id'), 'facility_admin_grants', ['user_id'], unique=False)
    op.create_table('professional_affiliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('role_function', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'suspended', 'ended', name='affiliationstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_affiliations_facility_id'), 'professional_affiliations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_professional_affiliations_professional_id'), 'professional_affiliations', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_affiliations_status'), 'professional_affiliations', ['status'], unique=False)
    op.add_column('professionals', sa.Column('verification_level', sa.Enum('unverified', 'identity_submitted', 'facility_matched', 'professional_pending', 'verified', 'facility_admin_verified', 'official_source_verified', 'rejected', 'suspended', 'duplicate_review', name='verificationlevel'), nullable=False, server_default='unverified'))
    # The ``role`` enum gained the ``verification_officer`` member. PostgreSQL
    # stores it as a native enum type, so the new value must be added explicitly;
    # SQLite stores enums as text and needs no change.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'verification_officer'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: a PostgreSQL enum value cannot be removed safely, so the
    # ``verification_officer`` member is intentionally left in place on downgrade.
    op.drop_column('professionals', 'verification_level')
    op.drop_index(op.f('ix_professional_affiliations_status'), table_name='professional_affiliations')
    op.drop_index(op.f('ix_professional_affiliations_professional_id'), table_name='professional_affiliations')
    op.drop_index(op.f('ix_professional_affiliations_facility_id'), table_name='professional_affiliations')
    op.drop_table('professional_affiliations')
    op.drop_index(op.f('ix_facility_admin_grants_user_id'), table_name='facility_admin_grants')
    op.drop_index(op.f('ix_facility_admin_grants_facility_id'), table_name='facility_admin_grants')
    op.drop_table('facility_admin_grants')
    op.drop_index(op.f('ix_verification_decisions_professional_id'), table_name='verification_decisions')
    op.drop_table('verification_decisions')
    op.drop_index(op.f('ix_professional_duplicate_flags_professional_id'), table_name='professional_duplicate_flags')
    op.drop_index(op.f('ix_professional_duplicate_flags_matched_professional_id'), table_name='professional_duplicate_flags')
    op.drop_table('professional_duplicate_flags')
    op.drop_index(op.f('ix_identity_documents_professional_id'), table_name='identity_documents')
    op.drop_table('identity_documents')
    op.drop_index(op.f('ix_healthcare_facilities_type'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_status'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_region'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_official_id'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_name'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_district'), table_name='healthcare_facilities')
    op.drop_table('healthcare_facilities')
    op.drop_table('registry_imports')
    # ### end Alembic commands ###
